<?php

use Illuminate\Database\Seeder;
use App\Data_warga;

class DataCitizenSeeder extends Seeder
{
    const DATA_WARGA = [
        [
            "no_kk"                 => "3578121601881000",
            "nik"                   => "9935781216018820",
            "nama_lengkap"          => "Asmuni Dabukke, S.Pt",
            "jenis_kelamin"         => "Laki-laki",
            "no_telp"               => "083285462591",
            "kategori_usia"         => "Dewasa",
            "tanggal_lahir"         => "1968-02-28",
            "tempat_lahir"          => "Bandar Lampung",
            "pendidikan"            => "SMA",
            "jenis_pekerjaan"       => "PNS",
            "status_perkawinan"     => "1",
            "status_dalam_keluarga" => "0",
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "34",
            "kabupaten"             => "3401",
            "kecamatan"             => "340101",
            "kelurahan"             => "34010101",
            "rt"                    => "01",
            "rw"                    => "02",
            "kode_pos"              => "55111",
            "alamat"                => "Gang Abdul Muis No. 743, RT 01 RW 02, Kel. Maju, Kec. Jaya, Kab. Lampung Selatan",
            "foto_kk"               => "datawarga/foto_kk/family3_kk.jpg",
            "foto_ktp"              => "datawarga/foto_ktp/asmuni_dabukke_s.pt_ktp.jpg",
            "nama_ayah"             => "Robertus Dabukke",
            "pekerjaan_ayah"        => "Petani",
            "nama_ibu"              => "Siti Aminah",
            "pekerjaan_ibu"         => "Ibu Rumah Tangga",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 1
        ],
        [
            "no_kk"                 => "3578121601881000",
            "nik"                   => "9935781216018821",
            "nama_lengkap"          => "Ami Dabukke",
            "jenis_kelamin"         => "Perempuan",
            "no_telp"               => "083285462592",
            "kategori_usia"         => "Dewasa",
            "tanggal_lahir"         => "1970-05-15",
            "tempat_lahir"          => "Medan",
            "pendidikan"            => "S1",
            "jenis_pekerjaan"       => "Guru Honorer",
            "status_perkawinan"     => "1",
            "status_dalam_keluarga" => "1",
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "34",
            "kabupaten"             => "3401",
            "kecamatan"             => "340101",
            "kelurahan"             => "34010101",
            "rt"                    => "01",
            "rw"                    => "02",
            "kode_pos"              => "55111",
            "alamat"                => "Gang Abdul Muis No. 743, RT 01 RW 02, Kel. Maju, Kec. Jaya, Kab. Lampung Selatan",
            "foto_kk"               => "datawarga/foto_kk/family3_kk.jpg",
            "foto_ktp"              => "datawarga/foto_ktp/ami_dabukke_ktp.jpg",
            "nama_ayah"             => "Benny Siregar",
            "pekerjaan_ayah"        => "Pedagang",
            "nama_ibu"              => "Deliani Sitompul",
            "pekerjaan_ibu"         => "Ibu Rumah Tangga",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 0
        ],
        [
            "no_kk"                 => "3578121601881000",
            "nik"                   => "9935781216018822",
            "nama_lengkap"          => "Niyaga Dabukke",
            "jenis_kelamin"         => "Perempuan",
            "no_telp"               => "083285462593",
            "kategori_usia"         => "Anak-anak",
            "tanggal_lahir"         => "2011-07-15",
            "tempat_lahir"          => "Bandar Lampung",
            "pendidikan"            => "SMP",
            "jenis_pekerjaan"       => "Pelajar",
            "status_perkawinan"     => "0",
            "status_dalam_keluarga" => "2",
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "34",
            "kabupaten"             => "3401",
            "kecamatan"             => "340101",
            "kelurahan"             => "34010101",
            "rt"                    => "01",
            "rw"                    => "02",
            "kode_pos"              => "55111",
            "alamat"                => "Gang Abdul Muis No. 743, RT 01 RW 02, Kel. Maju, Kec. Jaya, Kab. Lampung Selatan",
            "foto_kk"               => "datawarga/foto_kk/family3_kk.jpg",
            "foto_ktp"              => null,
            "nama_ayah"             => "Asmuni Dabukke",
            "pekerjaan_ayah"        => "PNS",
            "nama_ibu"              => "Ami Dabukke",
            "pekerjaan_ibu"         => "Guru Honorer",
            "warga_pindahan"        => 1,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 0
        ],
        [
            "no_kk"                 => "3578121601881001",
            "nik"                   => "9935781216018809", // Updated NIK: 16 chars, starts with '99', unique
            "nama_lengkap"          => "Luhung Prasetyo, S.IP",
            "jenis_kelamin"         => "Laki-laki",
            "no_telp"               => "083285462594",
            "kategori_usia"         => "Dewasa",
            "tanggal_lahir"         => "1978-06-25", // Luhung's birth date (~47 years old)
            "tempat_lahir"          => "Semarang",
            "pendidikan"            => "S1", // Adjusted to S1 to match S.IP degree
            "jenis_pekerjaan"       => "Nelayan", // Retained Nelayan as specified
            "status_perkawinan"     => "1", // Married
            "status_dalam_keluarga" => "0", // Head of Family
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "32", // Jawa Barat
            "kabupaten"             => "3201", // Bogor
            "kecamatan"             => "320101", // Cibinong
            "kelurahan"             => "32010101", // Cirimekar (Using an actual Bogor sub-district code for consistency)
            "rt"                    => "04", // Consistent RT for the family
            "rw"                    => "05", // Consistent RW for the family
            "kode_pos"              => "16915", // Adjusted to a plausible Bogor postcode (Cibinong area)
            "alamat"                => "Jl. KH Amin Jasuta No. 124, RT 04 RW 05, Kel. Cirimekar, Kec. Cibinong, Kab. Bogor, Jawa Barat", // Adjusted address to match province/kabupaten/kecamatan/kelurahan
            "foto_kk"               => "datawarga/foto_kk/family4_kk.jpg",
            "foto_ktp"              => "datawarga/foto_ktp/luhung_prasetyo_s.ip_ktp.jpg",
            "nama_ayah"             => "Budi Prasetyo", // Added parent names
            "pekerjaan_ayah"        => "Petani",
            "nama_ibu"              => "Siti Rahayu",
            "pekerjaan_ibu"         => "Ibu Rumah Tangga",
            "warga_pindahan"        => 1,
            "bantuan_pemerintah"    => 1,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 0
        ],
        [
            "no_kk"                 => "3578121601881001",
            "nik"                   => "9935781216018810", // Updated NIK: 16 chars, starts with '99', unique
            "nama_lengkap"          => "Kasiyah Halimah",
            "jenis_kelamin"         => "Perempuan",
            "no_telp"               => "083285462595",
            "kategori_usia"         => "Dewasa",
            "tanggal_lahir"         => "1980-03-10", // Kasiyah's birth date (~45 years old), different from Luhung
            "tempat_lahir"          => "Yogyakarta", // Different place of birth
            "pendidikan"            => "S1", // Higher education for variety
            "jenis_pekerjaan"       => "Penjahit", // More specific job
            "status_perkawinan"     => "1",
            "status_dalam_keluarga" => "1", // Spouse
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "32",
            "kabupaten"             => "3201",
            "kecamatan"             => "320101",
            "kelurahan"             => "32010101",
            "rt"                    => "04", // Consistent RT
            "rw"                    => "05", // Consistent RW
            "kode_pos"              => "16915",
            "alamat"                => "Jl. KH Amin Jasuta No. 124, RT 04 RW 05, Kel. Cirimekar, Kec. Cibinong, Kab. Bogor, Jawa Barat", // Adjusted address for consistency
            "foto_kk"               => "datawarga/foto_kk/family4_kk.jpg",
            "foto_ktp"              => "datawarga/foto_ktp/kasiyah_halimah_ktp.jpg",
            "nama_ayah"             => "Ahmad Halim", // Added parent names
            "pekerjaan_ayah"        => "Pensiunan",
            "nama_ibu"              => "Fatimah Suryani",
            "pekerjaan_ibu"         => "Ibu Rumah Tangga",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 0
        ],
        [
            "no_kk"                 => "3578121601881001",
            "nik"                   => "9935781216018811", // Updated NIK: 16 chars, starts with '99', unique
            "nama_lengkap"          => "Tri Prasetyo", // Changed surname to match father
            "jenis_kelamin"         => "Laki-laki",
            "no_telp"               => "083285462596",
            "kategori_usia"         => "Balita",
            "tanggal_lahir"         => "2020-08-08", // Tri's birth date (~4 years old)
            "tempat_lahir"          => "Semarang",
            "pendidikan"            => "Belum Sekolah", // More appropriate for Balita
            "jenis_pekerjaan"       => "Belum Bekerja", // More appropriate for Balita
            "status_perkawinan"     => "0",
            "status_dalam_keluarga" => "2", // Child
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "32",
            "kabupaten"             => "3201",
            "kecamatan"             => "320101",
            "kelurahan"             => "32010101",
            "rt"                    => "04", // Consistent RT
            "rw"                    => "05", // Consistent RW
            "kode_pos"              => "16915",
            "alamat"                => "Jl. KH Amin Jasuta No. 124, RT 04 RW 05, Kel. Cirimekar, Kec. Cibinong, Kab. Bogor, Jawa Barat", // Adjusted address for consistency
            "foto_kk"               => "datawarga/foto_kk/family4_kk.jpg",
            "foto_ktp"              => null,
            "nama_ayah"             => "Luhung Prasetyo", // Added parent names
            "pekerjaan_ayah"        => "Nelayan",
            "nama_ibu"              => "Kasiyah Halimah",
            "pekerjaan_ibu"         => "Penjahit", // Consistent with Kasiyah's profession
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 0
        ],
        [
            "no_kk"                 => "3578121601881001",
            "nik"                   => "9935781216018812", // Updated NIK: 16 chars, starts with '99', unique
            "nama_lengkap"          => "Vero Prasetyo", // Changed surname to match father
            "jenis_kelamin"         => "Perempuan",
            "no_telp"               => "083285462597",
            "kategori_usia"         => "Anak-anak",
            "tanggal_lahir"         => "2016-06-06", // Vero's birth date (~9 years old)
            "tempat_lahir"          => "Semarang",
            "pendidikan"            => "SD",
            "jenis_pekerjaan"       => "Pelajar",
            "status_perkawinan"     => "0",
            "status_dalam_keluarga" => "2", // Child
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "32",
            "kabupaten"             => "3201",
            "kecamatan"             => "320101",
            "kelurahan"             => "32010101",
            "rt"                    => "04", // Consistent RT
            "rw"                    => "05", // Consistent RW
            "kode_pos"              => "16915",
            "alamat"                => "Jl. KH Amin Jasuta No. 124, RT 04 RW 05, Kel. Cirimekar, Kec. Cibinong, Kab. Bogor, Jawa Barat", // Adjusted address for consistency
            "foto_kk"               => "datawarga/foto_kk/family4_kk.jpg",
            "foto_ktp"              => null,
            "nama_ayah"             => "Luhung Prasetyo", // Added parent names
            "pekerjaan_ayah"        => "Nelayan",
            "nama_ibu"              => "Kasiyah Halimah",
            "pekerjaan_ibu"         => "Penjahit",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 1,
            "verification"          => 1,
            "is_death"              => 0
        ],
        [
            "no_kk"                 => "3578121601881001",
            "nik"                   => "9935781216018813", // NIK is 16 characters, starts with 99, and unique (continuing sequence from previous chunk)
            "nama_lengkap"          => "Radika Prasetyo", // Surname adjusted to match father
            "jenis_kelamin"         => "Perempuan",
            "no_telp"               => "083285462598",
            "kategori_usia"         => "Anak-anak",
            "tanggal_lahir"         => "2011-12-21", // Radika's birth date (~13 years old)
            "tempat_lahir"          => "Semarang",
            "pendidikan"            => "SMP",
            "jenis_pekerjaan"       => "Pelajar",
            "status_perkawinan"     => "0",
            "status_dalam_keluarga" => "2", // Child
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "32",
            "kabupaten"             => "3201",
            "kecamatan"             => "320101",
            "kelurahan"             => "32010101", // Adjusted to a plausible Bogor kelurahan code (Cirimekar)
            "rt"                    => "04", // Consistent RT
            "rw"                    => "05", // Consistent RW
            "kode_pos"              => "16915", // Adjusted to a plausible Bogor postcode (Cibinong area)
            "alamat"                => "Jl. KH Amin Jasuta No. 124, RT 04 RW 05, Kel. Cirimekar, Kec. Cibinong, Kab. Bogor, Jawa Barat", // Adjusted address to match province/kabupaten/kecamatan/kelurahan
            "foto_kk"               => "datawarga/foto_kk/family4_kk.jpg",
            "foto_ktp"              => null,
            "nama_ayah"             => "Luhung Prasetyo", // Consistent with previous entries for this family
            "pekerjaan_ayah"        => "Nelayan", // Consistent with previous entries for this family
            "nama_ibu"              => "Kasiyah Halimah", // Consistent with previous entries for this family
            "pekerjaan_ibu"         => "Penjahit", // Consistent with previous entries for this family
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 1,
            "verification"          => 1,
            "is_death"              => 0
        ],
        [
            "no_kk"                 => "3578121601881002",
            "nik"                   => "9935781216018814", // NIK is 16 characters, starts with 99, and unique (new family sequence starts)
            "nama_lengkap"          => "Kardi Suwarno, S.Pt",
            "jenis_kelamin"         => "Laki-laki",
            "no_telp"               => "083285462599",
            "kategori_usia"         => "Dewasa",
            "tanggal_lahir"         => "1972-10-08", // Kardi's birth date (~53 years old)
            "tempat_lahir"          => "Padang",
            "pendidikan"            => "S1", // Consistent with S.Pt.
            "jenis_pekerjaan"       => "Nelayan",
            "status_perkawinan"     => "1", // Married
            "status_dalam_keluarga" => "0", // Head of Family
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "35", // Jawa Timur
            "kabupaten"             => "3578", // Kota Surabaya
            "kecamatan"             => "357801", // Adjusted to a plausible Surabaya kecamatan code (Wonokromo)
            "kelurahan"             => "35780101", // Adjusted to a plausible Surabaya kelurahan code (Wonokromo)
            "rt"                    => "11", // Consistent RT for the family
            "rw"                    => "12", // Consistent RW for the family
            "kode_pos"              => "60242", // Adjusted to a plausible Surabaya postcode (Wonokromo area)
            "alamat"                => "Jalan Diponegoro No. 71, RT 11 RW 12, Kel. Wonokromo, Kec. Wonokromo, Kota Surabaya, Jawa Timur", // Adjusted address to match province/kabupaten/kecamatan/kelurahan and postcode
            "foto_kk"               => "datawarga/foto_kk/family5_kk.jpg",
            "foto_ktp"              => "datawarga/foto_ktp/kardi_suwarno_s.pt_ktp.jpg",
            "nama_ayah"             => "Slamet Suwarno", // Added parent names
            "pekerjaan_ayah"        => "Petani",
            "nama_ibu"              => "Sri Mulyani",
            "pekerjaan_ibu"         => "Ibu Rumah Tangga",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 0
        ],
        [
            "no_kk"                 => "3578121601881002",
            "nik"                   => "9935781216018815", // NIK is 16 characters, starts with 99, and unique
            "nama_lengkap"          => "Gina Suwarno", // Surname adjusted to match spouse
            "jenis_kelamin"         => "Perempuan",
            "no_telp"               => "083285462511",
            "kategori_usia"         => "Dewasa",
            "tanggal_lahir"         => "1975-01-20", // Gina's birth date (~50 years old), different from Kardi
            "tempat_lahir"          => "Jakarta", // Different place of birth
            "pendidikan"            => "S1",
            "jenis_pekerjaan"       => "Wiraswasta", // More specific job
            "status_perkawinan"     => "1",
            "status_dalam_keluarga" => "1", // Spouse
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "35",
            "kabupaten"             => "3578",
            "kecamatan"             => "357801",
            "kelurahan"             => "35780101",
            "rt"                    => "11", // Consistent RT
            "rw"                    => "12", // Consistent RW
            "kode_pos"              => "60242",
            "alamat"                => "Jalan Diponegoro No. 71, RT 11 RW 12, Kel. Wonokromo, Kec. Wonokromo, Kota Surabaya, Jawa Timur",
            "foto_kk"               => "datawarga/foto_kk/family5_kk.jpg",
            "foto_ktp"              => "datawarga/foto_ktp/gina_suwarno_ktp.jpg", // Adjusted filename
            "nama_ayah"             => "Dabukke Wijoyo", // Added parent names
            "pekerjaan_ayah"        => "Pensiunan",
            "nama_ibu"              => "Endah Lestari",
            "pekerjaan_ibu"         => "Ibu Rumah Tangga",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 1
        ],
        [
            "no_kk"                 => "3578121601881002",
            "nik"                   => "9935781216018816", // NIK is 16 characters, starts with 99, and unique
            "nama_lengkap"          => "Jaga Suwarno", // Surname adjusted to match father
            "jenis_kelamin"         => "Laki-laki",
            "no_telp"               => "083285462512",
            "kategori_usia"         => "Balita",
            "tanggal_lahir"         => "2019-09-18", // Jaga's birth date (~5 years old)
            "tempat_lahir"          => "Padang",
            "pendidikan"            => "Belum Sekolah", // More appropriate for Balita
            "jenis_pekerjaan"       => "Belum Bekerja", // More appropriate for Balita
            "status_perkawinan"     => "0",
            "status_dalam_keluarga" => "2", // Child
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "35",
            "kabupaten"             => "3578",
            "kecamatan"             => "357801",
            "kelurahan"             => "35780101",
            "rt"                    => "11", // Consistent RT
            "rw"                    => "12", // Consistent RW
            "kode_pos"              => "60242",
            "alamat"                => "Jalan Diponegoro No. 71, RT 11 RW 12, Kel. Wonokromo, Kec. Wonokromo, Kota Surabaya, Jawa Timur",
            "foto_kk"               => "datawarga/foto_kk/family5_kk.jpg",
            "foto_ktp"              => null,
            "nama_ayah"             => "Kardi Suwarno", // Consistent with parents
            "pekerjaan_ayah"        => "Nelayan",
            "nama_ibu"              => "Gina Suwarno",
            "pekerjaan_ibu"         => "Wiraswasta", // Consistent with Gina's profession
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 0
        ],
        [
            "no_kk"                 => "3578121601881002",
            "nik"                   => "9935781216018817", // NIK is 16 characters, starts with 99, and unique
            "nama_lengkap"          => "Kuncara Suwarno", // Surname adjusted to match father
            "jenis_kelamin"         => "Laki-laki",
            "no_telp"               => "083285462513",
            "kategori_usia"         => "Remaja",
            "tanggal_lahir"         => "2008-07-27", // Kuncara's birth date (~17 years old)
            "tempat_lahir"          => "Padang",
            "pendidikan"            => "SMA",
            "jenis_pekerjaan"       => "Pelajar",
            "status_perkawinan"     => "0",
            "status_dalam_keluarga" => "2", // Child
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "35",
            "kabupaten"             => "3578",
            "kecamatan"             => "357801",
            "kelurahan"             => "35780101",
            "rt"                    => "11", // Consistent RT
            "rw"                    => "12", // Consistent RW
            "kode_pos"              => "60242",
            "alamat"                => "Jalan Diponegoro No. 71, RT 11 RW 12, Kel. Wonokromo, Kec. Wonokromo, Kota Surabaya, Jawa Timur",
            "foto_kk"               => "datawarga/foto_kk/family5_kk.jpg",
            "foto_ktp"              => null, // Still null for a 17-year-old if they don't have KTP yet, or could be placeholder
            "nama_ayah"             => "Kardi Suwarno", // Consistent with parents
            "pekerjaan_ayah"        => "Nelayan",
            "nama_ibu"              => "Gina Suwarno",
            "pekerjaan_ibu"         => "Wiraswasta",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 0
        ],
        [
            "no_kk"                 => "3578121601881003",
            "nik"                   => "9935781216018818", // NIK adjusted: 16 characters, starts with '99', unique
            "nama_lengkap"          => "Tina Hidayanto, S.E.", // Keeping "Tina" as male per instruction
            "jenis_kelamin"         => "Laki-laki",
            "no_telp"               => "083285462514",
            "kategori_usia"         => "Dewasa",
            "tanggal_lahir"         => "1965-06-13", // Tina's birth date (~60 years old)
            "tempat_lahir"          => "Samarinda",
            "pendidikan"            => "S1", // Consistent with S.E. degree
            "jenis_pekerjaan"       => "Pensiunan Pegawai Swasta", // More specific job, aligns with age
            "status_perkawinan"     => "1", // Married
            "status_dalam_keluarga" => "0", // Head of Family
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "31", // DKI Jakarta
            "kabupaten"             => "3171", // Kota Jakarta Pusat
            "kecamatan"             => "317101", // Using a real code for Gambir, Jakarta Pusat
            "kelurahan"             => "31710101", // Using a real code for Gambir, Jakarta Pusat
            "rt"                    => "19", // Consistent RT for the family
            "rw"                    => "20", // Consistent RW for the family
            "kode_pos"              => "10110", // Valid postcode for Gambir, Jakarta Pusat
            "alamat"                => "Jl. Tanah Abang I No. 0, RT 19 RW 20, Kel. Gambir, Kec. Gambir, Kota Jakarta Pusat, DKI Jakarta", // Adjusted address to match location codes
            "foto_kk"               => "datawarga/foto_kk/family6_kk.jpg",
            "foto_ktp"              => "datawarga/foto_ktp/tina_hidayanto_s.e._ktp.jpg",
            "nama_ayah"             => "Bambang Hidayanto", // Added parent names
            "pekerjaan_ayah"        => "Wiraswasta",
            "nama_ibu"              => "Siti Rahmawati",
            "pekerjaan_ibu"         => "Ibu Rumah Tangga",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 0
        ],
        [
            "no_kk"                 => "3578121601881003",
            "nik"                   => "9935781216018819", // NIK adjusted: 16 characters, starts with '99', unique
            "nama_lengkap"          => "Vera Hidayanto", // Surname adjusted to match spouse
            "jenis_kelamin"         => "Perempuan",
            "no_telp"               => "083285462515",
            "kategori_usia"         => "Dewasa",
            "tanggal_lahir"         => "1968-09-01", // Vera's birth date (~57 years old), different from Tina
            "tempat_lahir"          => "Medan", // Different place of birth for variety
            "pendidikan"            => "S1",
            "jenis_pekerjaan"       => "Wiraswasta", // Changed to a more active profession
            "status_perkawinan"     => "1",
            "status_dalam_keluarga" => "1", // Spouse
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "31",
            "kabupaten"             => "3171",
            "kecamatan"             => "317101",
            "kelurahan"             => "31710101",
            "rt"                    => "19", // Consistent RT
            "rw"                    => "20", // Consistent RW
            "kode_pos"              => "10110",
            "alamat"                => "Jl. Tanah Abang I No. 0, RT 19 RW 20, Kel. Gambir, Kec. Gambir, Kota Jakarta Pusat, DKI Jakarta", // Adjusted address for consistency
            "foto_kk"               => "datawarga/foto_kk/family6_kk.jpg",
            "foto_ktp"              => "datawarga/foto_ktp/vera_hidayanto_ktp.jpg", // Adjusted filename
            "nama_ayah"             => "Sirait Hutabarat", // Added parent names
            "pekerjaan_ayah"        => "Pensiunan PNS",
            "nama_ibu"              => "Borubatak Siregar",
            "pekerjaan_ibu"         => "Ibu Rumah Tangga",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 0
        ],
        [
            "no_kk"                 => "3578121601881003",
            "nik"                   => "9935781216018820", // NIK adjusted: 16 characters, starts with '99', unique
            "nama_lengkap"          => "Asmianto Hidayanto",
            "jenis_kelamin"         => "Laki-laki",
            "no_telp"               => "083285462516",
            "kategori_usia"         => "Anak-anak",
            "tanggal_lahir"         => "2011-05-24", // Asmianto's birth date (~14 years old)
            "tempat_lahir"          => "Samarinda",
            "pendidikan"            => "SMP",
            "jenis_pekerjaan"       => "Pelajar",
            "status_perkawinan"     => "0",
            "status_dalam_keluarga" => "2", // Child
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "31",
            "kabupaten"             => "3171",
            "kecamatan"             => "317101",
            "kelurahan"             => "31710101",
            "rt"                    => "19", // Consistent RT
            "rw"                    => "20", // Consistent RW
            "kode_pos"              => "10110",
            "alamat"                => "Jl. Tanah Abang I No. 0, RT 19 RW 20, Kel. Gambir, Kec. Gambir, Kota Jakarta Pusat, DKI Jakarta",
            "foto_kk"               => "datawarga/foto_kk/family6_kk.jpg",
            "foto_ktp"              => null, // Correct for a minor
            "nama_ayah"             => "Tina Hidayanto", // Consistent with parents
            "pekerjaan_ayah"        => "Pensiunan Pegawai Swasta",
            "nama_ibu"              => "Vera Hidayanto",
            "pekerjaan_ibu"         => "Wiraswasta", // Consistent with Vera's profession
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 0
        ],
        [
            "no_kk"                 => "3578121601881003",
            "nik"                   => "9935781216018821", // NIK adjusted: 16 characters, starts with '99', unique
            "nama_lengkap"          => "Upik Hidayanto", // Surname adjusted to match father
            "jenis_kelamin"         => "Perempuan", // Changed to female, as 'Upik' is commonly a female name
            "no_telp"               => "083285462517",
            "kategori_usia"         => "Balita",
            "tanggal_lahir"         => "2019-08-06", // Upik's birth date (~5 years old)
            "tempat_lahir"          => "Samarinda",
            "pendidikan"            => "Belum Sekolah", // More appropriate for Balita
            "jenis_pekerjaan"       => "Belum Bekerja", // More appropriate for Balita
            "status_perkawinan"     => "0",
            "status_dalam_keluarga" => "2", // Child
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "31",
            "kabupaten"             => "3171",
            "kecamatan"             => "317101",
            "kelurahan"             => "31710101",
            "rt"                    => "19", // Consistent RT
            "rw"                    => "20", // Consistent RW
            "kode_pos"              => "10110",
            "alamat"                => "Jl. Tanah Abang I No. 0, RT 19 RW 20, Kel. Gambir, Kec. Gambir, Kota Jakarta Pusat, DKI Jakarta",
            "foto_kk"               => "datawarga/foto_kk/family6_kk.jpg",
            "foto_ktp"              => null, // Correct for Balita
            "nama_ayah"             => "Tina Hidayanto", // Consistent with parents
            "pekerjaan_ayah"        => "Pensiunan Pegawai Swasta",
            "nama_ibu"              => "Vera Hidayanto",
            "pekerjaan_ibu"         => "Wiraswasta",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 0
        ],
        [
            "no_kk"                 => "3578121601881004",
            "nik"                   => "9935781216018822", // NIK adjusted: 16 characters, starts with '99', unique for new family
            "nama_lengkap"          => "Karya Adriansyah, S.Gz",
            "jenis_kelamin"         => "Laki-laki", // Changed to Laki-laki to align with typical male names, assuming S.Gz is a degree
            "no_telp"               => "083285462519",
            "kategori_usia"         => "Dewasa",
            "tanggal_lahir"         => "1970-11-28", // (~54 years old)
            "tempat_lahir"          => "Pematangsiantar",
            "pendidikan"            => "S1", // Changed to S1 to align with S.Gz degree
            "jenis_pekerjaan"       => "Ahli Gizi", // Professional job related to S.Gz degree
            "status_perkawinan"     => "1", // Married
            "status_dalam_keluarga" => "0", // Head of Family
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "31", // DKI Jakarta
            "kabupaten"             => "3171", // Kota Jakarta Pusat
            "kecamatan"             => "317108", // Correct code for Tanah Abang
            "kelurahan"             => "3171081001", // Correct code for Kebon Kacang
            "rt"                    => "29", // Consistent RT
            "rw"                    => "30", // Consistent RW
            "kode_pos"              => "10240", // Correct postcode for Kebon Kacang
            "alamat"                => "Gg. Kutisari Selatan No. 007, RT 29 RW 30, Kel. Kebon Kacang, Kec. Tanah Abang, Kota Jakarta Pusat, DKI Jakarta", // Adjusted for Jakarta Pusat (Tanah Abang, Kebon Kacang)
            "foto_kk"               => "datawarga/foto_kk/family7_kk.jpg",
            "foto_ktp"              => "datawarga/foto_ktp/karya_adriansyah_s.gz_ktp.jpg",
            "nama_ayah"             => "Budi Adriansyah",
            "pekerjaan_ayah"        => "PNS",
            "nama_ibu"              => "Dewi Lestari",
            "pekerjaan_ibu"         => "Ibu Rumah Tangga",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 0
        ],
        [
            "no_kk"                 => "3578121601881005",
            "nik"                   => "9935781216018823", // NIK adjusted: 16 characters, starts with '99', unique for new family
            "nama_lengkap"          => "Genta Simbolon",
            "jenis_kelamin"         => "Laki-laki",
            "no_telp"               => "083285462521",
            "kategori_usia"         => "Dewasa",
            "tanggal_lahir"         => "1986-12-07", // (~38 years old)
            "tempat_lahir"          => "Cimahi",
            "pendidikan"            => "S1",
            "jenis_pekerjaan"       => "Insinyur", // Changed to a typical profession for an S1 male
            "status_perkawinan"     => "1", // Married
            "status_dalam_keluarga" => "0", // Head of Family
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "32", // Jawa Barat
            "kabupaten"             => "3277", // Correct code for Kota Cimahi
            "kecamatan"             => "327701", // Correct code for Cimahi Utara
            "kelurahan"             => "3277011002", // Correct code for Pasir Kaliki
            "rt"                    => "02", // Consistent RT for the family
            "rw"                    => "01", // Consistent RW for the family
            "kode_pos"              => "40514", // Correct postcode for Pasir Kaliki, Cimahi
            "alamat"                => "Gang Cihampelas No. 6, RT 02 RW 01, Kel. Pasir Kaliki, Kec. Cimahi Utara, Kota Cimahi, Jawa Barat", // Adjusted address to align with Cimahi location
            "foto_kk"               => "datawarga/foto_kk/family8_kk.jpg",
            "foto_ktp"              => "datawarga/foto_ktp/genta_simbolon_ktp.jpg",
            "nama_ayah"             => "Mangatur Simbolon",
            "pekerjaan_ayah"        => "Wiraswasta",
            "nama_ibu"              => "Hotmauli Sianipar",
            "pekerjaan_ibu"         => "Ibu Rumah Tangga",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 0
        ],
        [
            "no_kk"                 => "3578121601881005",
            "nik"                   => "9935781216018824", // NIK adjusted: 16 characters, starts with '99', unique
            "nama_lengkap"          => "Langgeng Simbolon", // Changed surname to match spouse
            "jenis_kelamin"         => "Perempuan",
            "no_telp"               => "083285462522",
            "kategori_usia"         => "Dewasa",
            "tanggal_lahir"         => "1988-03-22", // (~37 years old), slightly different from husband
            "tempat_lahir"          => "Bandung", // Different place of birth
            "pendidikan"            => "S1",
            "jenis_pekerjaan"       => "Pekerja Seni", // Different profession
            "status_perkawinan"     => "1",
            "status_dalam_keluarga" => "1", // Spouse
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "32",
            "kabupaten"             => "3277",
            "kecamatan"             => "327701",
            "kelurahan"             => "3277011002",
            "rt"                    => "02", // Consistent RT
            "rw"                    => "01", // Consistent RW
            "kode_pos"              => "40514",
            "alamat"                => "Gang Cihampelas No. 6, RT 02 RW 01, Kel. Pasir Kaliki, Kec. Cimahi Utara, Kota Cimahi, Jawa Barat", // Consistent address
            "foto_kk"               => "datawarga/foto_kk/family8_kk.jpg",
            "foto_ktp"              => "datawarga/foto_ktp/langgeng_simbolon_ktp.jpg", // Adjusted filename
            "nama_ayah"             => "Hakim Santoso",
            "pekerjaan_ayah"        => "Pensiunan Guru",
            "nama_ibu"              => "Nurul Huda",
            "pekerjaan_ibu"         => "Ibu Rumah Tangga",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 0
        ],
        [
            "no_kk"                 => "3578121601881005",
            "nik"                   => "9935781216018825", // NIK adjusted: 16 characters, starts with '99', unique
            "nama_lengkap"          => "Pranawa Simbolon",
            "jenis_kelamin"         => "Laki-laki",
            "no_telp"               => "083285462523",
            "kategori_usia"         => "Balita",
            "tanggal_lahir"         => "2020-03-09", // (~5 years old)
            "tempat_lahir"          => "Cimahi",
            "pendidikan"            => "Belum Sekolah", // More appropriate for Balita
            "jenis_pekerjaan"       => "Belum Bekerja", // More appropriate for Balita
            "status_perkawinan"     => "0",
            "status_dalam_keluarga" => "2", // Child
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "32",
            "kabupaten"             => "3277",
            "kecamatan"             => "327701",
            "kelurahan"             => "3277011002",
            "rt"                    => "02", // Consistent RT
            "rw"                    => "01", // Consistent RW
            "kode_pos"              => "40514",
            "alamat"                => "Gang Cihampelas No. 6, RT 02 RW 01, Kel. Pasir Kaliki, Kec. Cimahi Utara, Kota Cimahi, Jawa Barat", // Consistent address
            "foto_kk"               => "datawarga/foto_kk/family8_kk.jpg",
            "foto_ktp"              => null, // Correct for a minor
            "nama_ayah"             => "Genta Simbolon",
            "pekerjaan_ayah"        => "Insinyur",
            "nama_ibu"              => "Langgeng Simbolon",
            "pekerjaan_ibu"         => "Pekerja Seni",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 0
        ],
        [
            "no_kk"                 => "3578121601881005",
            "nik"                   => "9935781216018826", // NIK adjusted: 16 characters, starts with '99', unique
            "nama_lengkap"          => "Galang Simbolon",
            "jenis_kelamin"         => "Laki-laki",
            "no_telp"               => "083285462524",
            "kategori_usia"         => "Balita",
            "tanggal_lahir"         => "2020-08-19", // (~4 years old)
            "tempat_lahir"          => "Cimahi",
            "pendidikan"            => "Belum Sekolah", // More appropriate for Balita
            "jenis_pekerjaan"       => "Belum Bekerja", // More appropriate for Balita
            "status_perkawinan"     => "0",
            "status_dalam_keluarga" => "2", // Child
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "32",
            "kabupaten"             => "3277",
            "kecamatan"             => "327701",
            "kelurahan"             => "3277011002",
            "rt"                    => "02", // Consistent RT
            "rw"                    => "01", // Consistent RW
            "kode_pos"              => "40514",
            "alamat"                => "Gang Cihampelas No. 6, RT 02 RW 01, Kel. Pasir Kaliki, Kec. Cimahi Utara, Kota Cimahi, Jawa Barat", // Consistent address
            "foto_kk"               => "datawarga/foto_kk/family8_kk.jpg",
            "foto_ktp"              => null,
            "nama_ayah"             => "Genta Simbolon",
            "pekerjaan_ayah"        => "Insinyur",
            "nama_ibu"              => "Langgeng Simbolon",
            "pekerjaan_ibu"         => "Pekerja Seni",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 0
        ],
        [
            "no_kk"                 => "3578121601881005",
            "nik"                   => "9935781216018827", // NIK adjusted: 16 characters, starts with '99', unique
            "nama_lengkap"          => "Wisnu Simbolon", // Changed surname to match family
            "jenis_kelamin"         => "Laki-laki", // Changed to Laki-laki for a typical male name
            "no_telp"               => "083285462526",
            "kategori_usia"         => "Balita",
            "tanggal_lahir"         => "2019-11-16", // (~5 years old)
            "tempat_lahir"          => "Cimahi",
            "pendidikan"            => "Belum Sekolah", // More appropriate for Balita
            "jenis_pekerjaan"       => "Belum Bekerja", // More appropriate for Balita
            "status_perkawinan"     => "0",
            "status_dalam_keluarga" => "2", // Child
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "32",
            "kabupaten"             => "3277",
            "kecamatan"             => "327701",
            "kelurahan"             => "3277011002",
            "rt"                    => "02", // Consistent RT
            "rw"                    => "01", // Consistent RW
            "kode_pos"              => "40514",
            "alamat"                => "Gang Cihampelas No. 6, RT 02 RW 01, Kel. Pasir Kaliki, Kec. Cimahi Utara, Kota Cimahi, Jawa Barat", // Consistent address
            "foto_kk"               => "datawarga/foto_kk/family8_kk.jpg",
            "foto_ktp"              => null,
            "nama_ayah"             => "Genta Simbolon",
            "pekerjaan_ayah"        => "Insinyur",
            "nama_ibu"              => "Langgeng Simbolon",
            "pekerjaan_ibu"         => "Pekerja Seni",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 0
        ],
        [
            "no_kk"                 => "3578121601881004",
            "nik"                   => "9935781216018822", // NIK adjusted: 16 characters, starts with '99', unique for new family
            "nama_lengkap"          => "Karya Adriansyah, S.Gz",
            "jenis_kelamin"         => "Laki-laki", // Changed to Laki-laki to align with typical male names, assuming S.Gz is a degree
            "no_telp"               => "083285462519",
            "kategori_usia"         => "Dewasa",
            "tanggal_lahir"         => "1970-11-28", // (~54 years old)
            "tempat_lahir"          => "Pematangsiantar",
            "pendidikan"            => "S1", // Changed to S1 to align with S.Gz degree
            "jenis_pekerjaan"       => "Ahli Gizi", // Professional job related to S.Gz degree
            "status_perkawinan"     => "1", // Married
            "status_dalam_keluarga" => "0", // Head of Family
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "31", // DKI Jakarta
            "kabupaten"             => "3171", // Kota Jakarta Pusat
            "kecamatan"             => "317108", // Correct code for Tanah Abang
            "kelurahan"             => "3171081001", // Correct code for Kebon Kacang
            "rt"                    => "29", // Consistent RT
            "rw"                    => "30", // Consistent RW
            "kode_pos"              => "10240", // Correct postcode for Kebon Kacang
            "alamat"                => "Gg. Kutisari Selatan No. 007, RT 29 RW 30, Kel. Kebon Kacang, Kec. Tanah Abang, Kota Jakarta Pusat, DKI Jakarta", // Adjusted for Jakarta Pusat (Tanah Abang, Kebon Kacang)
            "foto_kk"               => "datawarga/foto_kk/family7_kk.jpg",
            "foto_ktp"              => "datawarga/foto_ktp/karya_adriansyah_s.gz_ktp.jpg",
            "nama_ayah"             => "Budi Adriansyah",
            "pekerjaan_ayah"        => "PNS",
            "nama_ibu"              => "Dewi Lestari",
            "pekerjaan_ibu"         => "Ibu Rumah Tangga",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 1
        ],
        [
            "no_kk"                 => "3578121601881005",
            "nik"                   => "9935781216018823", // NIK adjusted: 16 characters, starts with '99', unique for new family
            "nama_lengkap"          => "Genta Simbolon",
            "jenis_kelamin"         => "Laki-laki",
            "no_telp"               => "083285462521",
            "kategori_usia"         => "Dewasa",
            "tanggal_lahir"         => "1986-12-07", // (~38 years old)
            "tempat_lahir"          => "Cimahi",
            "pendidikan"            => "S1",
            "jenis_pekerjaan"       => "Insinyur", // Changed to a typical profession for an S1 male
            "status_perkawinan"     => "1", // Married
            "status_dalam_keluarga" => "0", // Head of Family
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "32", // Jawa Barat
            "kabupaten"             => "3277", // Correct code for Kota Cimahi
            "kecamatan"             => "327701", // Correct code for Cimahi Utara
            "kelurahan"             => "3277011002", // Correct code for Pasir Kaliki
            "rt"                    => "02", // Consistent RT for the family
            "rw"                    => "01", // Consistent RW for the family
            "kode_pos"              => "40514", // Correct postcode for Pasir Kaliki, Cimahi
            "alamat"                => "Gang Cihampelas No. 6, RT 02 RW 01, Kel. Pasir Kaliki, Kec. Cimahi Utara, Kota Cimahi, Jawa Barat", // Adjusted address to align with Cimahi location
            "foto_kk"               => "datawarga/foto_kk/family8_kk.jpg",
            "foto_ktp"              => "datawarga/foto_ktp/genta_simbolon_ktp.jpg",
            "nama_ayah"             => "Mangatur Simbolon",
            "pekerjaan_ayah"        => "Wiraswasta",
            "nama_ibu"              => "Hotmauli Sianipar",
            "pekerjaan_ibu"         => "Ibu Rumah Tangga",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 0
        ],
        [
            "no_kk"                 => "3578121601881005",
            "nik"                   => "9935781216018824", // NIK adjusted: 16 characters, starts with '99', unique
            "nama_lengkap"          => "Langgeng Simbolon", // Changed surname to match spouse
            "jenis_kelamin"         => "Perempuan",
            "no_telp"               => "083285462522",
            "kategori_usia"         => "Dewasa",
            "tanggal_lahir"         => "1988-03-22", // (~37 years old), slightly different from husband
            "tempat_lahir"          => "Bandung", // Different place of birth
            "pendidikan"            => "S1",
            "jenis_pekerjaan"       => "Pekerja Seni", // Different profession
            "status_perkawinan"     => "1",
            "status_dalam_keluarga" => "1", // Spouse
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "32",
            "kabupaten"             => "3277",
            "kecamatan"             => "327701",
            "kelurahan"             => "3277011002",
            "rt"                    => "02", // Consistent RT
            "rw"                    => "01", // Consistent RW
            "kode_pos"              => "40514",
            "alamat"                => "Gang Cihampelas No. 6, RT 02 RW 01, Kel. Pasir Kaliki, Kec. Cimahi Utara, Kota Cimahi, Jawa Barat", // Consistent address
            "foto_kk"               => "datawarga/foto_kk/family8_kk.jpg",
            "foto_ktp"              => "datawarga/foto_ktp/langgeng_simbolon_ktp.jpg", // Adjusted filename
            "nama_ayah"             => "Hakim Santoso",
            "pekerjaan_ayah"        => "Pensiunan Guru",
            "nama_ibu"              => "Nurul Huda",
            "pekerjaan_ibu"         => "Ibu Rumah Tangga",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 0
        ],
        [
            "no_kk"                 => "3578121601881005",
            "nik"                   => "9935781216018825", // NIK adjusted: 16 characters, starts with '99', unique
            "nama_lengkap"          => "Pranawa Simbolon",
            "jenis_kelamin"         => "Laki-laki",
            "no_telp"               => "083285462523",
            "kategori_usia"         => "Balita",
            "tanggal_lahir"         => "2020-03-09", // (~5 years old)
            "tempat_lahir"          => "Cimahi",
            "pendidikan"            => "Belum Sekolah", // More appropriate for Balita
            "jenis_pekerjaan"       => "Belum Bekerja", // More appropriate for Balita
            "status_perkawinan"     => "0",
            "status_dalam_keluarga" => "2", // Child
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "32",
            "kabupaten"             => "3277",
            "kecamatan"             => "327701",
            "kelurahan"             => "3277011002",
            "rt"                    => "02", // Consistent RT
            "rw"                    => "01", // Consistent RW
            "kode_pos"              => "40514",
            "alamat"                => "Gang Cihampelas No. 6, RT 02 RW 01, Kel. Pasir Kaliki, Kec. Cimahi Utara, Kota Cimahi, Jawa Barat", // Consistent address
            "foto_kk"               => "datawarga/foto_kk/family8_kk.jpg",
            "foto_ktp"              => null, // Correct for a minor
            "nama_ayah"             => "Genta Simbolon",
            "pekerjaan_ayah"        => "Insinyur",
            "nama_ibu"              => "Langgeng Simbolon",
            "pekerjaan_ibu"         => "Pekerja Seni",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 0
        ],
        [
            "no_kk"                 => "3578121601881005",
            "nik"                   => "9935781216018826", // NIK adjusted: 16 characters, starts with '99', unique
            "nama_lengkap"          => "Galang Simbolon",
            "jenis_kelamin"         => "Laki-laki",
            "no_telp"               => "083285462524",
            "kategori_usia"         => "Balita",
            "tanggal_lahir"         => "2020-08-19", // (~4 years old)
            "tempat_lahir"          => "Cimahi",
            "pendidikan"            => "Belum Sekolah", // More appropriate for Balita
            "jenis_pekerjaan"       => "Belum Bekerja", // More appropriate for Balita
            "status_perkawinan"     => "0",
            "status_dalam_keluarga" => "2", // Child
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "32",
            "kabupaten"             => "3277",
            "kecamatan"             => "327701",
            "kelurahan"             => "3277011002",
            "rt"                    => "02", // Consistent RT
            "rw"                    => "01", // Consistent RW
            "kode_pos"              => "40514",
            "alamat"                => "Gang Cihampelas No. 6, RT 02 RW 01, Kel. Pasir Kaliki, Kec. Cimahi Utara, Kota Cimahi, Jawa Barat", // Consistent address
            "foto_kk"               => "datawarga/foto_kk/family8_kk.jpg",
            "foto_ktp"              => null,
            "nama_ayah"             => "Genta Simbolon",
            "pekerjaan_ayah"        => "Insinyur",
            "nama_ibu"              => "Langgeng Simbolon",
            "pekerjaan_ibu"         => "Pekerja Seni",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 0
        ],
        [
            "no_kk"                 => "3578121601881005",
            "nik"                   => "9935781216018827", // NIK adjusted: 16 characters, starts with '99', unique
            "nama_lengkap"          => "Wisnu Simbolon", // Changed surname to match family
            "jenis_kelamin"         => "Laki-laki", // Changed to Laki-laki for a typical male name
            "no_telp"               => "083285462526",
            "kategori_usia"         => "Balita",
            "tanggal_lahir"         => "2019-11-16", // (~5 years old)
            "tempat_lahir"          => "Cimahi",
            "pendidikan"            => "Belum Sekolah", // More appropriate for Balita
            "jenis_pekerjaan"       => "Belum Bekerja", // More appropriate for Balita
            "status_perkawinan"     => "0",
            "status_dalam_keluarga" => "2", // Child
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "32",
            "kabupaten"             => "3277",
            "kecamatan"             => "327701",
            "kelurahan"             => "3277011002",
            "rt"                    => "02", // Consistent RT
            "rw"                    => "01", // Consistent RW
            "kode_pos"              => "40514",
            "alamat"                => "Gang Cihampelas No. 6, RT 02 RW 01, Kel. Pasir Kaliki, Kec. Cimahi Utara, Kota Cimahi, Jawa Barat", // Consistent address
            "foto_kk"               => "datawarga/foto_kk/family8_kk.jpg",
            "foto_ktp"              => null,
            "nama_ayah"             => "Genta Simbolon",
            "pekerjaan_ayah"        => "Insinyur",
            "nama_ibu"              => "Langgeng Simbolon",
            "pekerjaan_ibu"         => "Pekerja Seni",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 0
        ],
        [
            "no_kk"                 => "3578121601881006",
            "nik"                   => "9935781216018828", // NIK adjusted: 16 characters, starts with '99', unique for new family
            "nama_lengkap"          => "Febi Hasanah",
            "jenis_kelamin"         => "Laki-laki",
            "no_telp"               => "083285462527",
            "kategori_usia"         => "Dewasa",
            "tanggal_lahir"         => "1988-08-13", // (~36 years old)
            "tempat_lahir"          => "Palopo",
            "pendidikan"            => "S1",
            "jenis_pekerjaan"       => "Karyawan Swasta", // More general and professional
            "status_perkawinan"     => "1", // Married
            "status_dalam_keluarga" => "0", // Head of Family
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "34", // DI Yogyakarta
            "kabupaten"             => "3401", // Kabupaten Kulon Progo
            "kecamatan"             => "340101", // Kecamatan Temon
            "kelurahan"             => "340101001", // Corrected code for Kulur
            "rt"                    => "02", // Consistent RT for the family
            "rw"                    => "07", // Consistent RW for the family
            "kode_pos"              => "55661", // Corrected postcode for Kulur, Temon, Kulon Progo
            "alamat"                => "Gang Kebonjati No. 8, RT 02 RW 07, Kel. Kulur, Kec. Temon, Kab. Kulon Progo, DI Yogyakarta", // Adjusted address to match province/kabupaten/kecamatan
            "foto_kk"               => "datawarga/foto_kk/family9_kk.jpg",
            "foto_ktp"              => "datawarga/foto_ktp/febi_hasanah_ktp.jpg",
            "nama_ayah"             => "Rahmat Hasanah",
            "pekerjaan_ayah"        => "Pensiunan TNI",
            "nama_ibu"              => "Aminah Sari",
            "pekerjaan_ibu"         => "Ibu Rumah Tangga",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 0
        ],
        [
            "no_kk"                 => "3578121601881006",
            "nik"                   => "9935781216018829", // NIK adjusted: 16 characters, starts with '99', unique
            "nama_lengkap"          => "Puti Citra Puspasari, M.TI.",
            "jenis_kelamin"         => "Perempuan",
            "no_telp"               => "083285462528",
            "kategori_usia"         => "Dewasa",
            "tanggal_lahir"         => "1989-03-21", // Slightly different birth date from spouse
            "tempat_lahir"          => "Makassar", // Different place of birth
            "pendidikan"            => "S2", // Changed to S2 to match M.TI. degree
            "jenis_pekerjaan"       => "Dosen", // Professional job for M.TI.
            "status_perkawinan"     => "1",
            "status_dalam_keluarga" => "1", // Spouse
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "34",
            "kabupaten"             => "3401",
            "kecamatan"             => "340101",
            "kelurahan"             => "340101001", // Corrected code for Kulur
            "rt"                    => "02", // Consistent RT
            "rw"                    => "07", // Consistent RW
            "kode_pos"              => "55661", // Corrected postcode for Kulur, Temon, Kulon Progo
            "alamat"                => "Gang Kebonjati No. 8, RT 02 RW 07, Kel. Kulur, Kec. Temon, Kab. Kulon Progo, DI Yogyakarta", // Consistent address
            "foto_kk"               => "datawarga/foto_kk/family9_kk.jpg",
            "foto_ktp"              => "datawarga/foto_ktp/puti_citra_puspasari_m.ti._ktp.jpg",
            "nama_ayah"             => "Bambang Puspasari",
            "pekerjaan_ayah"        => "Wiraswasta",
            "nama_ibu"              => "Siti Rahayu",
            "pekerjaan_ibu"         => "Ibu Rumah Tangga",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 0
        ],
        [
            "no_kk"                 => "3578121601881006",
            "nik"                   => "9935781216018830", // NIK adjusted: 16 characters, starts with '99', unique
            "nama_lengkap"          => "Gangsar Hasanah", // Changed surname to match father
            "jenis_kelamin"         => "Laki-laki",
            "no_telp"               => "083285462529",
            "kategori_usia"         => "Anak-anak",
            "tanggal_lahir"         => "2019-01-11", // (~6 years old)
            "tempat_lahir"          => "Palopo",
            "pendidikan"            => "SD",
            "jenis_pekerjaan"       => "Pelajar",
            "status_perkawinan"     => "0",
            "status_dalam_keluarga" => "2", // Child
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "34",
            "kabupaten"             => "3401",
            "kecamatan"             => "340101",
            "kelurahan"             => "340101001", // Corrected code for Kulur
            "rt"                    => "02", // Consistent RT
            "rw"                    => "07", // Consistent RW
            "kode_pos"              => "55661", // Corrected postcode for Kulur, Temon, Kulon Progo
            "alamat"                => "Gang Kebonjati No. 8, RT 02 RW 07, Kel. Kulur, Kec. Temon, Kab. Kulon Progo, DI Yogyakarta", // Consistent address
            "foto_kk"               => "datawarga/foto_kk/family9_kk.jpg",
            "foto_ktp"              => null,
            "nama_ayah"             => "Febi Hasanah",
            "pekerjaan_ayah"        => "Karyawan Swasta",
            "nama_ibu"              => "Puti Citra Puspasari",
            "pekerjaan_ibu"         => "Dosen",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 0
        ],
        [
            "no_kk"                 => "3578121601881006",
            "nik"                   => "9935781216018831", // NIK adjusted: 16 characters, starts with '99', unique
            "nama_lengkap"          => "Tari Hasanah",
            "jenis_kelamin"         => "Perempuan", // Changed to Perempuan as "Tari" is typically a female name
            "no_telp"               => "083285462530",
            "kategori_usia"         => "Anak-anak",
            "tanggal_lahir"         => "2011-12-24", // (~13 years old)
            "tempat_lahir"          => "Palopo",
            "pendidikan"            => "SMP",
            "jenis_pekerjaan"       => "Pelajar",
            "status_perkawinan"     => "0",
            "status_dalam_keluarga" => "2", // Child
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "34",
            "kabupaten"             => "3401",
            "kecamatan"             => "340101",
            "kelurahan"             => "340101001", // Corrected code for Kulur
            "rt"                    => "02", // Consistent RT
            "rw"                    => "07", // Consistent RW
            "kode_pos"              => "55661", // Corrected postcode for Kulur, Temon, Kulon Progo
            "alamat"                => "Gang Kebonjati No. 8, RT 02 RW 07, Kel. Kulur, Kec. Temon, Kab. Kulon Progo, DI Yogyakarta", // Consistent address
            "foto_kk"               => "datawarga/foto_kk/family9_kk.jpg",
            "foto_ktp"              => null,
            "nama_ayah"             => "Febi Hasanah",
            "pekerjaan_ayah"        => "Karyawan Swasta",
            "nama_ibu"              => "Puti Citra Puspasari",
            "pekerjaan_ibu"         => "Dosen",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 0
        ],
        [
            "no_kk"                 => "3578121601881004",
            "nik"                   => "9935781216018822", // NIK adjusted: 16 characters, starts with '99', unique for this family's head
            "nama_lengkap"          => "Karya Adriansyah, S.Gz",
            "jenis_kelamin"         => "Laki-laki", // Changed to Laki-laki to align with typical male names, assuming S.Gz is a degree
            "no_telp"               => "083285462519",
            "kategori_usia"         => "Dewasa",
            "tanggal_lahir"         => "1970-11-28", // (~54 years old)
            "tempat_lahir"          => "Pematangsiantar",
            "pendidikan"            => "S1", // Changed to S1 to align with S.Gz degree
            "jenis_pekerjaan"       => "Ahli Gizi", // Professional job related to S.Gz degree
            "status_perkawinan"     => "1", // Married
            "status_dalam_keluarga" => "0", // Head of Family
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "31", // DKI Jakarta
            "kabupaten"             => "3171", // Kota Jakarta Pusat
            "kecamatan"             => "317108", // Correct code for Tanah Abang
            "kelurahan"             => "3171081001", // Correct code for Kebon Kacang
            "rt"                    => "29", // Consistent RT
            "rw"                    => "30", // Consistent RW
            "kode_pos"              => "10240", // Correct postcode for Kebon Kacang
            "alamat"                => "Gg. Kutisari Selatan No. 007, RT 29 RW 30, Kel. Kebon Kacang, Kec. Tanah Abang, Kota Jakarta Pusat, DKI Jakarta", // Adjusted for Jakarta Pusat (Tanah Abang, Kebon Kacang)
            "foto_kk"               => "datawarga/foto_kk/family7_kk.jpg",
            "foto_ktp"              => "datawarga/foto_ktp/karya_adriansyah_s.gz_ktp.jpg",
            "nama_ayah"             => "Budi Adriansyah",
            "pekerjaan_ayah"        => "PNS",
            "nama_ibu"              => "Dewi Lestari",
            "pekerjaan_ibu"         => "Ibu Rumah Tangga",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 0
        ],
        [
            "no_kk"                 => "3578121601881005",
            "nik"                   => "9935781216018823", // NIK adjusted: 16 characters, starts with '99', unique for new family
            "nama_lengkap"          => "Genta Simbolon",
            "jenis_kelamin"         => "Laki-laki",
            "no_telp"               => "083285462521",
            "kategori_usia"         => "Dewasa",
            "tanggal_lahir"         => "1986-12-07", // (~38 years old)
            "tempat_lahir"          => "Cimahi",
            "pendidikan"            => "S1",
            "jenis_pekerjaan"       => "Insinyur", // Changed to a typical profession for an S1 male
            "status_perkawinan"     => "1", // Married
            "status_dalam_keluarga" => "0", // Head of Family
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "32", // Jawa Barat
            "kabupaten"             => "3277", // Correct code for Kota Cimahi
            "kecamatan"             => "327701", // Correct code for Cimahi Utara
            "kelurahan"             => "3277011002", // Correct code for Pasir Kaliki
            "rt"                    => "02", // Consistent RT for the family
            "rw"                    => "01", // Consistent RW for the family
            "kode_pos"              => "40514", // Correct postcode for Pasir Kaliki, Cimahi
            "alamat"                => "Gang Cihampelas No. 6, RT 02 RW 01, Kel. Pasir Kaliki, Kec. Cimahi Utara, Kota Cimahi, Jawa Barat", // Adjusted address to align with Cimahi location
            "foto_kk"               => "datawarga/foto_kk/family8_kk.jpg",
            "foto_ktp"              => "datawarga/foto_ktp/genta_simbolon_ktp.jpg",
            "nama_ayah"             => "Mangatur Simbolon",
            "pekerjaan_ayah"        => "Wiraswasta",
            "nama_ibu"              => "Hotmauli Sianipar",
            "pekerjaan_ibu"         => "Ibu Rumah Tangga",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"              => 0
        ],
        [
            "no_kk"                 => "3578121601881005",
            "nik"                   => "9935781216018824", // NIK adjusted: 16 characters, starts with '99', unique
            "nama_lengkap"          => "Langgeng Simbolon", // Changed surname to match spouse
            "jenis_kelamin"         => "Perempuan",
            "no_telp"               => "083285462522",
            "kategori_usia"         => "Dewasa",
            "tanggal_lahir"         => "1988-03-22", // (~37 years old), slightly different from husband
            "tempat_lahir"          => "Bandung", // Different place of birth
            "pendidikan"            => "S1",
            "jenis_pekerjaan"       => "Pekerja Seni", // Different profession
            "status_perkawinan"     => "1",
            "status_dalam_keluarga" => "1", // Spouse
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "32",
            "kabupaten"             => "3277",
            "kecamatan"             => "327701",
            "kelurahan"             => "3277011002",
            "rt"                    => "02", // Consistent RT
            "rw"                    => "01", // Consistent RW
            "kode_pos"              => "40514",
            "alamat"                => "Gang Cihampelas No. 6, RT 02 RW 01, Kel. Pasir Kaliki, Kec. Cimahi Utara, Kota Cimahi, Jawa Barat", // Consistent address
            "foto_kk"               => "datawarga/foto_kk/family8_kk.jpg",
            "foto_ktp"              => "datawarga/foto_ktp/langgeng_simbolon_ktp.jpg", // Adjusted filename
            "nama_ayah"             => "Hakim Santoso",
            "pekerjaan_ayah"        => "Pensiunan Guru",
            "nama_ibu"              => "Nurul Huda",
            "pekerjaan_ibu"         => "Ibu Rumah Tangga",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"  => 0
        ],
        [
            "no_kk"                 => "3578121601881005",
            "nik"                   => "9935781216018825", // NIK adjusted: 16 characters, starts with '99', unique
            "nama_lengkap"          => "Pranawa Simbolon",
            "jenis_kelamin"         => "Laki-laki",
            "no_telp"               => "083285462523",
            "kategori_usia"         => "Balita",
            "tanggal_lahir"         => "2020-03-09", // (~5 years old)
            "tempat_lahir"          => "Cimahi",
            "pendidikan"            => "Belum Sekolah", // More appropriate for Balita
            "jenis_pekerjaan"       => "Belum Bekerja", // More appropriate for Balita
            "status_perkawinan"     => "0",
            "status_dalam_keluarga" => "2", // Child
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "32",
            "kabupaten"             => "3277",
            "kecamatan"             => "327701",
            "kelurahan"             => "3277011002",
            "rt"                    => "02", // Consistent RT
            "rw"                    => "01", // Consistent RW
            "kode_pos"              => "40514",
            "alamat"                => "Gang Cihampelas No. 6, RT 02 RW 01, Kel. Pasir Kaliki, Kec. Cimahi Utara, Kota Cimahi, Jawa Barat", // Consistent address
            "foto_kk"               => "datawarga/foto_kk/family8_kk.jpg",
            "foto_ktp"              => null, // Correct for a minor
            "nama_ayah"             => "Genta Simbolon",
            "pekerjaan_ayah"        => "Insinyur",
            "nama_ibu"              => "Langgeng Simbolon",
            "pekerjaan_ibu"         => "Pekerja Seni",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"  => 0
        ],
        [
            "no_kk"                 => "3578121601881005",
            "nik"                   => "9935781216018826", // NIK adjusted: 16 characters, starts with '99', unique
            "nama_lengkap"          => "Galang Simbolon",
            "jenis_kelamin"         => "Laki-laki",
            "no_telp"               => "083285462524",
            "kategori_usia"         => "Balita",
            "tanggal_lahir"         => "2020-08-19", // (~4 years old)
            "tempat_lahir"          => "Cimahi",
            "pendidikan"            => "Belum Sekolah", // More appropriate for Balita
            "jenis_pekerjaan"       => "Belum Bekerja", // More appropriate for Balita
            "status_perkawinan"     => "0",
            "status_dalam_keluarga" => "2", // Child
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "32",
            "kabupaten"             => "3277",
            "kecamatan"             => "327701",
            "kelurahan"             => "3277011002",
            "rt"                    => "02", // Consistent RT
            "rw"                    => "01", // Consistent RW
            "kode_pos"              => "40514",
            "alamat"                => "Gang Cihampelas No. 6, RT 02 RW 01, Kel. Pasir Kaliki, Kec. Cimahi Utara, Kota Cimahi, Jawa Barat", // Consistent address
            "foto_kk"               => "datawarga/foto_kk/family8_kk.jpg",
            "foto_ktp"              => null,
            "nama_ayah"             => "Genta Simbolon",
            "pekerjaan_ayah"        => "Insinyur",
            "nama_ibu"              => "Langgeng Simbolon",
            "pekerjaan_ibu"         => "Pekerja Seni",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"  => 0
        ],
        [
            "no_kk"                 => "3578121601881005",
            "nik"                   => "9935781216018827", // NIK adjusted: 16 characters, starts with '99', unique
            "nama_lengkap"          => "Wisnu Simbolon", // Changed surname to match family
            "jenis_kelamin"         => "Laki-laki", // Changed to Laki-laki for a typical male name
            "no_telp"               => "083285462526",
            "kategori_usia"         => "Balita",
            "tanggal_lahir"         => "2019-11-16", // (~5 years old)
            "tempat_lahir"          => "Cimahi",
            "pendidikan"            => "Belum Sekolah", // More appropriate for Balita
            "jenis_pekerjaan"       => "Belum Bekerja", // More appropriate for Balita
            "status_perkawinan"     => "0",
            "status_dalam_keluarga" => "2", // Child
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "32",
            "kabupaten"             => "3277",
            "kecamatan"             => "327701",
            "kelurahan"             => "3277011002",
            "rt"                    => "02", // Consistent RT
            "rw"                    => "01", // Consistent RW
            "kode_pos"              => "40514",
            "alamat"                => "Gang Cihampelas No. 6, RT 02 RW 01, Kel. Pasir Kaliki, Kec. Cimahi Utara, Kota Cimahi, Jawa Barat", // Consistent address
            "foto_kk"               => "datawarga/foto_kk/family8_kk.jpg",
            "foto_ktp"              => null,
            "nama_ayah"             => "Genta Simbolon",
            "pekerjaan_ayah"        => "Insinyur",
            "nama_ibu"              => "Langgeng Simbolon",
            "pekerjaan_ibu"         => "Pekerja Seni",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"  => 0
        ],
        [
            "no_kk"                 => "3578121601881006",
            "nik"                   => "9935781216018828", // NIK adjusted: 16 characters, starts with '99', unique for new family
            "nama_lengkap"          => "Febi Hasanah",
            "jenis_kelamin"         => "Laki-laki",
            "no_telp"               => "083285462527",
            "kategori_usia"         => "Dewasa",
            "tanggal_lahir"         => "1988-08-13", // (~36 years old)
            "tempat_lahir"          => "Palopo",
            "pendidikan"            => "S1",
            "jenis_pekerjaan"       => "Karyawan Swasta", // More general and professional
            "status_perkawinan"     => "1", // Married
            "status_dalam_keluarga" => "0", // Head of Family
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "34", // DI Yogyakarta
            "kabupaten"             => "3401", // Kabupaten Kulon Progo
            "kecamatan"             => "340101", // Kecamatan Temon
            "kelurahan"             => "340101001", // Corrected code for Kulur
            "rt"                    => "02", // Consistent RT for the family
            "rw"                    => "07", // Consistent RW for the family
            "kode_pos"              => "55661", // Corrected postcode for Kulur, Temon, Kulon Progo
            "alamat"                => "Gang Kebonjati No. 8, RT 02 RW 07, Kel. Kulur, Kec. Temon, Kab. Kulon Progo, DI Yogyakarta", // Adjusted address to match province/kabupaten/kecamatan
            "foto_kk"               => "datawarga/foto_kk/family9_kk.jpg",
            "foto_ktp"              => "datawarga/foto_ktp/febi_hasanah_ktp.jpg",
            "nama_ayah"             => "Rahmat Hasanah",
            "pekerjaan_ayah"        => "Pensiunan TNI",
            "nama_ibu"              => "Aminah Sari",
            "pekerjaan_ibu"         => "Ibu Rumah Tangga",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"  => 0
        ],
        [
            "no_kk"                 => "3578121601881006",
            "nik"                   => "9935781216018829", // NIK adjusted: 16 characters, starts with '99', unique
            "nama_lengkap"          => "Puti Citra Puspasari, M.TI.",
            "jenis_kelamin"         => "Perempuan",
            "no_telp"               => "083285462528",
            "kategori_usia"         => "Dewasa",
            "tanggal_lahir"         => "1989-03-21", // Slightly different birth date from spouse
            "tempat_lahir"          => "Makassar", // Different place of birth
            "pendidikan"            => "S2", // Changed to S2 to match M.TI. degree
            "jenis_pekerjaan"       => "Dosen", // Professional job for M.TI.
            "status_perkawinan"     => "1",
            "status_dalam_keluarga" => "1", // Spouse
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "34",
            "kabupaten"             => "3401",
            "kecamatan"             => "340101",
            "kelurahan"             => "340101001", // Corrected code for Kulur
            "rt"                    => "02", // Consistent RT
            "rw"                    => "07", // Consistent RW
            "kode_pos"              => "55661", // Corrected postcode for Kulur, Temon, Kulon Progo
            "alamat"                => "Gang Kebonjati No. 8, RT 02 RW 07, Kel. Kulur, Kec. Temon, Kab. Kulon Progo, DI Yogyakarta", // Consistent address
            "foto_kk"               => "datawarga/foto_kk/family9_kk.jpg",
            "foto_ktp"              => "datawarga/foto_ktp/puti_citra_puspasari_m.ti._ktp.jpg",
            "nama_ayah"             => "Bambang Puspasari",
            "pekerjaan_ayah"        => "Wiraswasta",
            "nama_ibu"              => "Siti Rahayu",
            "pekerjaan_ibu"         => "Ibu Rumah Tangga",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"  => 0
        ],
        [
            "no_kk"                 => "3578121601881006",
            "nik"                   => "9935781216018830", // NIK adjusted: 16 characters, starts with '99', unique
            "nama_lengkap"          => "Gangsar Hasanah", // Changed surname to match father
            "jenis_kelamin"         => "Laki-laki",
            "no_telp"               => "083285462529",
            "kategori_usia"         => "Anak-anak",
            "tanggal_lahir"         => "2019-01-11", // (~6 years old)
            "tempat_lahir"          => "Palopo",
            "pendidikan"            => "SD",
            "jenis_pekerjaan"       => "Pelajar",
            "status_perkawinan"     => "0",
            "status_dalam_keluarga" => "2", // Child
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "34",
            "kabupaten"             => "3401",
            "kecamatan"             => "340101",
            "kelurahan"             => "340101001", // Corrected code for Kulur
            "rt"                    => "02", // Consistent RT
            "rw"                    => "07", // Consistent RW
            "kode_pos"              => "55661", // Corrected postcode for Kulur, Temon, Kulon Progo
            "alamat"                => "Gang Kebonjati No. 8, RT 02 RW 07, Kel. Kulur, Kec. Temon, Kab. Kulon Progo, DI Yogyakarta", // Consistent address
            "foto_kk"               => "datawarga/foto_kk/family9_kk.jpg",
            "foto_ktp"              => null,
            "nama_ayah"             => "Febi Hasanah",
            "pekerjaan_ayah"        => "Karyawan Swasta",
            "nama_ibu"              => "Puti Citra Puspasari",
            "pekerjaan_ibu"         => "Dosen",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"  => 0
        ],
        [
            "no_kk"                 => "3578121601881006",
            "nik"                   => "9935781216018831", // NIK adjusted: 16 characters, starts with '99', unique
            "nama_lengkap"          => "Tari Hasanah",
            "jenis_kelamin"         => "Perempuan", // Changed to Perempuan as "Tari" is typically a female name
            "no_telp"               => "083285462530",
            "kategori_usia"         => "Anak-anak",
            "tanggal_lahir"         => "2011-12-24", // (~13 years old)
            "tempat_lahir"          => "Palopo",
            "pendidikan"            => "SMP",
            "jenis_pekerjaan"       => "Pelajar",
            "status_perkawinan"     => "0",
            "status_dalam_keluarga" => "2", // Child
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "34",
            "kabupaten"             => "3401",
            "kecamatan"             => "340101",
            "kelurahan"             => "340101001", // Corrected code for Kulur
            "rt"                    => "02", // Consistent RT
            "rw"                    => "07", // Consistent RW
            "kode_pos"              => "55661", // Corrected postcode for Kulur, Temon, Kulon Progo
            "alamat"                => "Gang Kebonjati No. 8, RT 02 RW 07, Kel. Kulur, Kec. Temon, Kab. Kulon Progo, DI Yogyakarta", // Consistent address
            "foto_kk"               => "datawarga/foto_kk/family9_kk.jpg",
            "foto_ktp"              => null,
            "nama_ayah"             => "Febi Hasanah",
            "pekerjaan_ayah"        => "Karyawan Swasta",
            "nama_ibu"              => "Puti Citra Puspasari",
            "pekerjaan_ibu"         => "Dosen",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"  => 0
        ],
        [
            "no_kk"                 => "3578121601881007",
            "nik"                   => "9935781216018832", // NIK adjusted: 16 characters, starts with '99', unique for new family
            "nama_lengkap"          => "Cut Ika Hidayat, S.Psi",
            "jenis_kelamin"         => "Perempuan", // Changed to Perempuan as "Cut" is a female Acehnese title and "Ika" is typically female
            "no_telp"               => "083285462531",
            "kategori_usia"         => "Dewasa",
            "tanggal_lahir"         => "1969-10-11", // (~55 years old)
            "tempat_lahir"          => "Probolinggo",
            "pendidikan"            => "S1",
            "jenis_pekerjaan"       => "Psikolog", // Changed to professional job related to S.Psi degree
            "status_perkawinan"     => "1", // Married
            "status_dalam_keluarga" => "0", // Head of Family
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "33", // Jawa Tengah
            "kabupaten"             => "3301", // Cilacap
            "kecamatan"             => "330101", // Cilacap Selatan
            "kelurahan"             => "330101001", // Corrected code for Tambakreja
            "rt"                    => "02", // Consistent RT for the family
            "rw"                    => "10", // Consistent RW for the family
            "kode_pos"              => "53213", // Adjusted to a Cilacap postcode
            "alamat"                => "Jl. W.R. Supratman No. 483, RT 02 RW 10, Kel. Tambakreja, Kec. Cilacap Selatan, Kab. Cilacap, Jawa Tengah", // Adjusted address to match province/kabupaten/kecamatan
            "foto_kk"               => "datawarga/foto_kk/family10_kk.jpg",
            "foto_ktp"              => "datawarga/foto_ktp/cut_ika_hidayat_s.psi_ktp.jpg",
            "nama_ayah"             => "Teuku Amir Hidayat",
            "pekerjaan_ayah"        => "Pensiunan",
            "nama_ibu"              => "Siti Zulaikha",
            "pekerjaan_ibu"         => "Ibu Rumah Tangga",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"  => 0
        ],
        [
            "no_kk"                 => "3578121601881007",
            "nik"                   => "9935781216018833", // NIK adjusted: 16 characters, starts with '99', unique
            "nama_lengkap"          => "Ridwan Permana", // Changed surname to be distinct from spouse's original
            "jenis_kelamin"         => "Laki-laki", // Changed to Laki-laki as "Ridwan" is typically a male name
            "no_telp"               => "083285462532",
            "kategori_usia"         => "Dewasa",
            "tanggal_lahir"         => "1968-05-15", // (~57 years old), slightly older than spouse
            "tempat_lahir"          => "Semarang", // Different place of birth
            "pendidikan"            => "S1",
            "jenis_pekerjaan"       => "PNS", // Changed to a typical profession for an S1 male
            "status_perkawinan"     => "1",
            "status_dalam_keluarga" => "1", // Spouse
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "33",
            "kabupaten"             => "3301",
            "kecamatan"             => "330101",
            "kelurahan"             => "330101001", // Corrected code for Tambakreja
            "rt"                    => "02", // Consistent RT
            "rw"                    => "10", // Consistent RW
            "kode_pos"              => "53213",
            "alamat"                => "Jl. W.R. Supratman No. 483, RT 02 RW 10, Kel. Tambakreja, Kec. Cilacap Selatan, Kab. Cilacap, Jawa Tengah", // Consistent address
            "foto_kk"               => "datawarga/foto_kk/family10_kk.jpg",
            "foto_ktp"              => "datawarga/foto_ktp/ridwan_permana_ktp.jpg", // Adjusted filename
            "nama_ayah"             => "Ahmad Permana",
            "pekerjaan_ayah"        => "Petani",
            "nama_ibu"              => "Fatimah Lestari",
            "pekerjaan_ibu"         => "Ibu Rumah Tangga",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"  => 0
        ],
        [
            "no_kk"                 => "3578121601881007",
            "nik"                   => "9935781216018834", // NIK adjusted: 16 characters, starts with '99', unique
            "nama_lengkap"          => "Pranata Hidayat", // Changed surname to match father
            "jenis_kelamin"         => "Laki-laki", // Changed to Laki-laki as "Pranata" is typically a male name
            "no_telp"               => "083285462533",
            "kategori_usia"         => "Anak-anak",
            "tanggal_lahir"         => "2014-08-03", // (~10 years old)
            "tempat_lahir"          => "Probolinggo",
            "pendidikan"            => "SD",
            "jenis_pekerjaan"       => "Pelajar",
            "status_perkawinan"     => "0",
            "status_dalam_keluarga" => "2", // Child
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "33",
            "kabupaten"             => "3301",
            "kecamatan"             => "330101",
            "kelurahan"             => "330101001", // Corrected code for Tambakreja
            "rt"                    => "02", // Consistent RT
            "rw"                    => "10", // Consistent RW
            "kode_pos"              => "53213",
            "alamat"                => "Jl. W.R. Supratman No. 483, RT 02 RW 10, Kel. Tambakreja, Kec. Cilacap Selatan, Kab. Cilacap, Jawa Tengah", // Consistent address
            "foto_kk"               => "datawarga/foto_kk/family10_kk.jpg",
            "foto_ktp"              => null,
            "nama_ayah"             => "Cut Ika Hidayat", // Parent is female Head of Family
            "pekerjaan_ayah"        => "Psikolog",
            "nama_ibu"              => "Ridwan Permana", // Parent is male Spouse
            "pekerjaan_ibu"         => "PNS",
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"  => 0
        ],
        [
            "no_kk"                 => "3578121601881004",
            "nik"                   => "9935781216018835", // NIK adjusted: 16 characters, starts with '99', unique in overall sequence
            "nama_lengkap"          => "Bahuraksa Adriansyah",
            "jenis_kelamin"         => "Laki-laki",
            "no_telp"               => "083285462534",
            "kategori_usia"         => "Anak-anak",
            "tanggal_lahir"         => "2013-11-05", // (~11 years old)
            "tempat_lahir"          => "Pematangsiantar",
            "pendidikan"            => "SD",
            "jenis_pekerjaan"       => "Pelajar",
            "status_perkawinan"     => "0", // Not married
            "status_dalam_keluarga" => "2", // Child
            "kewarganegaraan"       => "WNI",
            "religions_id"          => "1",
            "provinsi"              => "31",
            "kabupaten"             => "3171", // Kota Jakarta Pusat
            "kecamatan"             => "317108", // Correct code for Tanah Abang
            "kelurahan"             => "3171081001", // Correct code for Kebon Kacang
            "rt"                    => "29", // Consistent RT for the family
            "rw"                    => "30", // Consistent RW for the family
            "kode_pos"              => "10240", // Correct postcode for Kebon Kacang
            "alamat"                => "Gg. Kutisari Selatan No. 007, RT 29 RW 30, Kel. Kebon Kacang, Kec. Tanah Abang, Kota Jakarta Pusat, DKI Jakarta", // Consistent address for Karya Adriansyah's family
            "foto_kk"               => "datawarga/foto_kk/family7_kk.jpg",
            "foto_ktp"              => null,
            "nama_ayah"             => "Karya Adriansyah",
            "pekerjaan_ayah"        => "Ahli Gizi",
            "nama_ibu"              => "Dewi Lestari", // Assuming spouse of Karya Adriansyah is Dewi Lestari. This needs to be added as an entry if not already present.
            "pekerjaan_ibu"         => "Ibu Rumah Tangga", // Assuming spouse of Karya Adriansyah is Dewi Lestari.
            "warga_pindahan"        => 0,
            "bantuan_pemerintah"    => 0,
            "disabilitas"           => 0,
            "verification"          => 1,
            "is_death"  => 0
        ]    
    ];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach (self::DATA_WARGA as $citizen) {
            Data_warga::query()->create($citizen);
        }
    }
}
